# Generated by Django 4.1.10 on 2023-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveBigIntegerField(max_length=255)),
                ('photo', models.FileField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
