# Generated by Django 4.1.10 on 2023-08-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='crud',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='images/%Y/%m/%d/'),
        ),
    ]
